[32mINFO[0m:     [28-03-2025 22:14:32] Set chroma_server_nofile to 65535
[32mINFO[0m:     [28-03-2025 22:14:32] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [28-03-2025 22:14:32] Starting component System
[36mDEBUG[0m:    [28-03-2025 22:14:32] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [28-03-2025 22:14:32] Starting component SqliteDB
[36mDEBUG[0m:    [28-03-2025 22:14:32] Starting component SimpleQuotaEnforcer
[36mDEBUG[0m:    [28-03-2025 22:14:32] Starting component Posthog
[36mDEBUG[0m:    [28-03-2025 22:14:32] Starting component SimpleRateLimitEnforcer
[36mDEBUG[0m:    [28-03-2025 22:14:32] Starting component LocalSegmentManager
[36mDEBUG[0m:    [28-03-2025 22:14:32] Starting component LocalExecutor
[36mDEBUG[0m:    [28-03-2025 22:14:32] Starting component SegmentAPI
[32mINFO[0m:     [28-03-2025 22:14:32] Started server process [[36m5891[0m]
[32mINFO[0m:     [28-03-2025 22:14:32] Waiting for application startup.
[32mINFO[0m:     [28-03-2025 22:14:32] Application startup complete.
[32mINFO[0m:     [28-03-2025 22:14:32] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [28-03-2025 22:15:12] ::1:63973 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:15:12] ::1:63974 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:15:12] ::1:63974 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:15:12] ::1:63973 - "DELETE /api/v2/tenants/default_tenant/databases/default_database/collections/rag_collection HTTP/1.1" 400
[31mERROR[0m:    [28-03-2025 22:15:12] Exception in ASGI application
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 147, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 743, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 181, in __call__
    raise app_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 140, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 181, in __call__
    raise app_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 107, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 153, in call_next
    raise app_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 140, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 173, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 175, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 131, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 153, in call_next
    raise app_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 140, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 134, in async_wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 779, in delete_collection
    await to_thread.run_sync(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 150, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/api/segment.py", line 103, in wrapper
    return self._rate_limit_enforcer.rate_limit(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/rate_limit/simple_rate_limit/__init__.py", line 23, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/api/segment.py", line 392, in delete_collection
    raise ValueError(f"Collection {name} does not exist.")
ValueError: Collection rag_collection does not exist.
[32mINFO[0m:     [28-03-2025 22:19:00] ::1:64089 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:19:00] ::1:64090 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:19:00] ::1:64090 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:19:00] ::1:64089 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:19:02] ::1:64089 - "GET /api/v2/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [28-03-2025 22:19:02] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [28-03-2025 22:19:02] ::1:64089 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/8a5d0db0-9edf-4bad-a4c8-2801e1f081bb/add HTTP/1.1" 201
[32mINFO[0m:     [28-03-2025 22:19:02] ::1:64089 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/8a5d0db0-9edf-4bad-a4c8-2801e1f081bb/add HTTP/1.1" 201
[32mINFO[0m:     [28-03-2025 22:19:04] ::1:64089 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/8a5d0db0-9edf-4bad-a4c8-2801e1f081bb/add HTTP/1.1" 201
[32mINFO[0m:     [28-03-2025 22:19:38] ::1:64150 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:19:38] ::1:64151 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:19:38] ::1:64151 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[36mDEBUG[0m:    [28-03-2025 22:19:38] Collection rag_collection already exists, returning existing collection.
[32mINFO[0m:     [28-03-2025 22:19:38] ::1:64150 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:19:38] ::1:64150 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/8a5d0db0-9edf-4bad-a4c8-2801e1f081bb/query HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:43:44] Set chroma_server_nofile to 65535
[32mINFO[0m:     [28-03-2025 22:43:44] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [28-03-2025 22:43:44] Starting component System
[36mDEBUG[0m:    [28-03-2025 22:43:44] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [28-03-2025 22:43:44] Starting component SqliteDB
[36mDEBUG[0m:    [28-03-2025 22:43:44] Starting component SimpleQuotaEnforcer
[36mDEBUG[0m:    [28-03-2025 22:43:44] Starting component Posthog
[36mDEBUG[0m:    [28-03-2025 22:43:44] Starting component SimpleRateLimitEnforcer
[36mDEBUG[0m:    [28-03-2025 22:43:44] Starting component LocalSegmentManager
[36mDEBUG[0m:    [28-03-2025 22:43:44] Starting component LocalExecutor
[36mDEBUG[0m:    [28-03-2025 22:43:44] Starting component SegmentAPI
[32mINFO[0m:     [28-03-2025 22:43:44] Started server process [[36m893[0m]
[32mINFO[0m:     [28-03-2025 22:43:44] Waiting for application startup.
[32mINFO[0m:     [28-03-2025 22:43:44] Application startup complete.
[32mINFO[0m:     [28-03-2025 22:43:44] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [28-03-2025 22:44:33] ::1:49210 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:44:33] ::1:49211 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:44:33] ::1:49211 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:44:33] ::1:49210 - "GET /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:44:33] ::1:49210 - "GET /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:44:33] ::1:49210 - "DELETE /api/v2/tenants/default_tenant/databases/default_database/collections/rag_collection HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:44:33] ::1:49210 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:44:34] ::1:49210 - "GET /api/v2/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [28-03-2025 22:44:34] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [28-03-2025 22:44:34] ::1:49210 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/678181c8-4e7a-4a2b-a4a2-0f6466b1a4b9/add HTTP/1.1" 201
[32mINFO[0m:     [28-03-2025 22:44:34] ::1:49210 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/678181c8-4e7a-4a2b-a4a2-0f6466b1a4b9/add HTTP/1.1" 201
[32mINFO[0m:     [28-03-2025 22:44:36] ::1:49210 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/678181c8-4e7a-4a2b-a4a2-0f6466b1a4b9/add HTTP/1.1" 201
[32mINFO[0m:     [28-03-2025 22:45:13] ::1:49258 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:45:13] ::1:49259 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:45:13] ::1:49259 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[36mDEBUG[0m:    [28-03-2025 22:45:13] Collection rag_collection already exists, returning existing collection.
[32mINFO[0m:     [28-03-2025 22:45:13] ::1:49258 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:45:13] ::1:49258 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/678181c8-4e7a-4a2b-a4a2-0f6466b1a4b9/query HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:45:57] ::1:49273 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:45:57] ::1:49274 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:45:57] ::1:49274 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[36mDEBUG[0m:    [28-03-2025 22:45:57] Collection rag_collection already exists, returning existing collection.
[32mINFO[0m:     [28-03-2025 22:45:57] ::1:49273 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:45:57] ::1:49273 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/678181c8-4e7a-4a2b-a4a2-0f6466b1a4b9/query HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:46:24] ::1:49282 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:46:24] ::1:49283 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:46:24] ::1:49283 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[36mDEBUG[0m:    [28-03-2025 22:46:24] Collection rag_collection already exists, returning existing collection.
[32mINFO[0m:     [28-03-2025 22:46:24] ::1:49282 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:46:24] ::1:49282 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/678181c8-4e7a-4a2b-a4a2-0f6466b1a4b9/query HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:46:45] ::1:49291 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:46:45] ::1:49292 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:46:45] ::1:49292 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[36mDEBUG[0m:    [28-03-2025 22:46:45] Collection rag_collection already exists, returning existing collection.
[32mINFO[0m:     [28-03-2025 22:46:45] ::1:49291 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:46:45] ::1:49291 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/678181c8-4e7a-4a2b-a4a2-0f6466b1a4b9/query HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:47:18] ::1:49300 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:47:18] ::1:49301 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:47:18] ::1:49301 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[36mDEBUG[0m:    [28-03-2025 22:47:18] Collection rag_collection already exists, returning existing collection.
[32mINFO[0m:     [28-03-2025 22:47:18] ::1:49300 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:47:18] ::1:49300 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/678181c8-4e7a-4a2b-a4a2-0f6466b1a4b9/query HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:48:40] ::1:49310 - "GET /api/v2/auth/identity HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:48:40] ::1:49311 - "GET /api/v2/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:48:40] ::1:49311 - "GET /api/v2/tenants/default_tenant/databases/default_database HTTP/1.1" 200
[36mDEBUG[0m:    [28-03-2025 22:48:40] Collection rag_collection already exists, returning existing collection.
[32mINFO[0m:     [28-03-2025 22:48:40] ::1:49310 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections HTTP/1.1" 200
[32mINFO[0m:     [28-03-2025 22:48:40] ::1:49310 - "POST /api/v2/tenants/default_tenant/databases/default_database/collections/678181c8-4e7a-4a2b-a4a2-0f6466b1a4b9/query HTTP/1.1" 200
